### ISSUE TITLE
No such module 'TextToSpeechV1'

### ISSUE THREAD

**Issue by flatworld21** [watson-developer-cloud/speech-to-text-swift#10]
/Users/user/Documents/text-to-speech-swift/Text to Speech/ViewController.swift:19:8: No such module 'TextToSpeechV1'

**Comment by glennrfisher** [comment]
Hi @flatworld21. Given the references to Text to Speech, I think this issue was intended for the [text-to-speech-swift repository][1]. But I'll answer it here.

The `TextToSpeechV1` module is missing because you have not built it using the dependency manager, Carthage. Make sure you [install Carthage][2] then run `carthage update --platform iOS` from the project directory, as specified in the [setup instructions][3].

[1]: https://github.com/watson-developer-cloud/text-to-speech-swift
[2]: https://github.com/Carthage/Carthage#installing-carthage
[3]: https://github.com/watson-developer-cloud/text-to-speech-swift#setup
