### ISSUE TITLE
Airpods not working as input

### ISSUE THREAD

**Issue by donpironet** [watson-developer-cloud/speech-to-text-swift#21]
Hi,

Is it possible that recording via Airpods is not supported? Because it seems that watson is always taking the devices microphone even when the Airpods are connected.

I don't see a way to change this or verify.

**Comment by donnacha1560** [comment]
some further info on this usecase:
So we are using the swift SDK and I use the method recognizeMicrophone.
The phone is in the operating room and a nurse pushes the watson button when she sees that the surgeon wants to say something. The surgeon wears Apple Airpods in his helmet and he can speak.

The problem is that the library takes the microphone from the phone instead of the Airpods as input for the voice. So the nurse is standing a couple of meters aways and there is ofcourse a little bit of noise in the room. So watson doesn't understand what the surgeon says. What we want is that I can configure the library to use the bluetooth airpods from apple als input or that the library detects that there is a bluetooth source as input available that it uses that one that's fine as well.

**Comment by jeff-arn** [comment]
This is being closed as this repo has been deprecated. If you had a question that arose through this issue that has not been answered, we recommend that you ask on Stack Overflow with the `IBM Watson` tag, or on [IBM DeveloperWorks Answers](https://developer.ibm.com/answers) with the tag `WATSON`
